brokers:
  - id: broker1
    address: "0.0.0.0:8081"

  - id: broker2
    address: "0.0.0.0:8082"

  - id: broker3
    address: "0.0.0.0:8083"

  - id: broker4
    address: "0.0.0.0:8084"

  - id: broker5
    address: "0.0.0.0:8085"

  - id: broker6
    address: "0.0.0.0:8086"
